# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "slate"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
logo = "img/site-logo-transparent.png"

# mainSections = ["section1", "section2"]
robots = "all"

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true

[article]
  showDate = true
  #showViews = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = false
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = false 
  showWordCount = false
  showSummary = true
  sharingLinks = [ "twitter", "reddit", "email"]

[list]
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = false
  groupByYear = true

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true

[firebase]
  apiKey = "AIzaSyB6OURlzO3UNtZAfYZ4nGYsL6R2RQC5g1U"
  authDomain = "the-gray-blog.firebaseapp.com"
  projectId = "the-gray-blog"
  storageBucket = "the-gray-blog.appspot.com"
  messagingSenderId = "642218646329"
  appId = "1:642218646329:web:709597eab6d0efb0eaa6e8"
  measurementId = "G-TB59WMPTH1"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
